### ISSUE TITLE
serious bug about tag showing list

### ISSUE THREAD

**Issue by rhinenoir** [rangzf/vscode-ghost-theme#1]
There always are some “anonymous" stories 
At first I found one story didn't show in its tags, I then edit its publish date to make an update so that I can see it in the tags......but then another story disappeared from its tags!
I repeat it for several times......**every time one story comes back to normal another story will disappear like ghost**

my site:
[http://ghost.garenfeather.cn/](http://ghost.garenfeather.cn/)

one ghost-like story:
[ghost.garenfeather.cn/backend-question-schedule/](ghost.garenfeather.cn/backend-question-schedule/)
it has tow tags: `backend` , `question`, its title: `进度：开放型后端开发随机聊天话题大全（误）`
but as you can see:
![fail to show](https://media.discordapp.net/attachments/420095259125743637/427296435973652500/ULBC06CZ46K2T0A90.png)

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Joffey** [comment]
Thanks for your feedback, I reproduced this problem
`get` helper shows 15 posts by default
`limit="all"` solved this problem, and you can update now

**Comment by rhinenoir** [comment]
@rangzf it works! many thx to you!

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
